spring:

  datasource:
    username: root
    password: 123456
#    username: root
#    password: 8c84774ada469edf
    url: jdbc:mysql://localhost:3306/xiangliban?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.xiangliban.managementsystem.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081
  servlet:
    context-path: /xiangliban
